apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-utils-productpage-certificate
  namespace: istio-system
spec:
  secretName: cert-utils-productpage-certificate
  commonName: productpage-with-service-mesh.apps.ocp.ocp-gm.de
  dnsNames:
    - productpage-with-service-mesh.apps.ocp.ocp-gm.de
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer