{{- if or (eq .Values.phase "instance-green-mesh") (eq .Values.phase "instance-red-mesh") (eq .Values.phase "instance-blue-mesh") }}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: {{ include "app.currentmeshsystemnamespace" . }} 
spec:
  members:
  - {{ include "app.deploymentnamespace" . }}
{{- end }}