apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/cert-utils-operator.cert-utils-operator: ""
    name: cert-utils-operator
    namespace: cert-utils-operator
  spec:
    channel: alpha
    installPlanApproval: Automatic
    name: cert-utils-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cert-utils-operator.v1.3.11
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/jaeger-product.openshift-distributed-tracing: ""
    name: jaeger-product
    namespace: openshift-distributed-tracing
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: jaeger-product
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: jaeger-operator.v1.42.0-5-0.1687199951.p
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    annotations:
      olm.generated-by: install-9mhc9
    labels:
      operators.coreos.com/rhsso-operator.openshift-mta: ""
    name: rhsso-operator-stable-redhat-operators-openshift-marketplace
    namespace: openshift-mta
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: rhsso-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhsso-operator.7.6.3-opr-002
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
    name: elasticsearch-operator
    namespace: openshift-operators-redhat
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: elasticsearch-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: elasticsearch-operator.v5.7.3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/amq-broker-rhel8.openshift-operators: ""
    name: amq-broker-rhel8
    namespace: openshift-operators
  spec:
    channel: 7.11.x
    installPlanApproval: Automatic
    name: amq-broker-rhel8
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: amq-broker-operator.v7.11.0-opr-3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/amq-streams.openshift-operators: ""
    name: amq-streams
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: amq-streams
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: amqstreams.v2.4.0-0
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/cert-manager.openshift-operators: ""
    name: cert-manager
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: cert-manager
    source: community-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cert-manager.v1.12.2
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/devspaces.openshift-operators: ""
    name: devspaces
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: devspacesoperator.v3.6.0-0.1685322634.p
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    annotations:
      olm.generated-by: install-gkcgp
    labels:
      operators.coreos.com/devworkspace-operator.openshift-operators: ""
    name: devworkspace-operator-fast-redhat-operators-openshift-marketplace
    namespace: openshift-operators
  spec:
    channel: fast
    installPlanApproval: Automatic
    name: devworkspace-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: devworkspace-operator.v0.20.0
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/kiali-ossm.openshift-operators: ""
    name: kiali-ossm
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: kiali-ossm
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kiali-operator.v1.65.7
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
    name: openshift-gitops-operator
    namespace: openshift-operators
  spec:
    channel: latest
    installPlanApproval: Automatic
    name: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: openshift-gitops-operator.v1.8.3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
    name: openshift-pipelines-operator-rh
    namespace: openshift-operators
  spec:
    channel: latest
    installPlanApproval: Automatic
    name: openshift-pipelines-operator-rh
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: openshift-pipelines-operator-rh.v1.10.3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/servicemeshoperator.openshift-operators: ""
    name: servicemeshoperator
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: servicemeshoperator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: servicemeshoperator.v2.4.1
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/serverless-operator.openshift-serverless: ""
    name: serverless-operator
    namespace: openshift-serverless
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: serverless-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: serverless-operator.v1.29.0
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/rhacs-operator.rhacs-operator: ""
    name: rhacs-operator
    namespace: rhacs-operator
  spec:
    channel: latest
    installPlanApproval: Automatic
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhacs-operator.v3.74.5
kind: List
metadata:
  resourceVersion: ""
