phase: federation # green-mesh | red-mesh | federation-green-mesh | federation-red-mesh | instance-green-mesh | instance-red-mesh | prep

nameGreenmesh: green-mesh
nameClusterGreenmesh: green-cluster
namespaceGreenmeshSystem: green-mesh-system
namespaceGreenmesh: gm-greenmesh-public
addressGreenmesh: "af00f888dcfa649e29751eddca469e08-521566250.us-east-2.elb.amazonaws.com"
addressGreenmeshDeployment: "productpage-with-service-mesh.apps.xyhm32jt.eastus2.aroapp.io"

nameRedmesh: red-mesh
nameClusterRedmesh: red-cluster
namespaceRedmeshSystem: red-mesh-system
namespaceRedmesh: gm-redmesh-private
addressRedmesh: "20.122.233.230"

clusterIssuerEmail: 'modzelewski.georg@gmail.com'

disableLetsencrypt: false